/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "main.h"
extern const U8 RyzenImage[26454];
extern const U8 NvidiaImage[30054];
extern const U8 RamImage[30054];
extern struct systemInfo_s SystemInfo;
#define GUI_MAKE_COLOR(ABGR)  (((((U32)ABGR) & 0xFF000000ul) ^ 0xFF000000ul) | ((((U32)ABGR) & 0x00FF0000ul) >> 16) | (((U32)ABGR) & 0x0000FF00ul) | ((((U32)ABGR) & 0x000000FFul) << 16))
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define LCD_SIZE_X       480
#define LCD_SIZE_Y       272
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x00)
#define ID_IMAGE_0    (GUI_ID_USER + 0x04) //Ryzen Image
#define ID_IMAGE_1    (GUI_ID_USER + 0x05) //Nvidia Image
#define ID_IMAGE_2    (GUI_ID_USER + 0x07) // RAM Image
#define ID_TEXT_0    (GUI_ID_USER + 0x08) //RYZEN CPU Info Text
#define ID_TEXT_1    (GUI_ID_USER + 0x09) //RYZEN Temp Text
#define ID_TEXT_2    (GUI_ID_USER + 0x0A)
#define ID_TEXT_3    (GUI_ID_USER + 0x0B)
#define ID_PROGBAR_RAM (GUI_ID_USER + 0x0C)

#define ID_IMAGE_0_IMAGE_0   0x00
#define ID_IMAGE_1_IMAGE_0   0x01
#define ID_IMAGE_2_IMAGE_0   0x02

// USER START (Optionally insert additional defines)
struct gui_handle_s
{
	TEXT_Handle RyzenTempTxtHandle;
	TEXT_Handle NvidiaTempTxtHandle;
	TEXT_Handle RAMUsageTxtHandle;
	PROGBAR_Handle RAMUsageProgHandle;
}GUIHandle;
// USER END
PROGBAR_SKINFLEX_PROPS RAMUsagProgBarSkinFlex;
/*********************************************************************
*
*       Static data
*
**********************************************************************/

// USER START (Optionally insert additional public code)
// USER END
void CreateSystemMonitor(void)
{
	IMAGE_Handle ImgHandle;
	TEXT_Handle TxtHandle;
	//Draw three rectangles
	GUI_SetColor(GUI_RED);
	GUI_DrawRoundedRect(0,0, (LCD_SIZE_X/2)-1, LCD_SIZE_Y-72, 10);
	GUI_SetColor(GUI_GREEN);
	GUI_DrawRoundedRect((LCD_SIZE_X/2)+1, 0, LCD_SIZE_X- 2, LCD_SIZE_Y - 72, 10);
	GUI_SetColor(GUI_CYAN);
	GUI_DrawRoundedRect(0, LCD_SIZE_Y - 70, LCD_SIZE_X- 2, LCD_SIZE_Y -2, 10);
	
	//Add Ryzen BMP image
	ImgHandle = IMAGE_CreateEx(10,10, 100, 90, 0, WM_CF_SHOW, 0, ID_IMAGE_0);
	IMAGE_SetBMP(ImgHandle, RyzenImage, sizeof(RyzenImage));
	
	//Add Nvidia BMP image
	ImgHandle = IMAGE_CreateEx((LCD_SIZE_X/2)+10,10, 100, 90, 0, WM_CF_SHOW, 0, ID_IMAGE_1);
	IMAGE_SetBMP(ImgHandle, NvidiaImage, sizeof(NvidiaImage));
	
	//Add RAM BMP image
	ImgHandle = IMAGE_CreateEx(10,LCD_SIZE_Y - 65, 200, 50, 0, WM_CF_SHOW, 0, ID_IMAGE_2);
	IMAGE_SetBMP(ImgHandle, RamImage, sizeof(RamImage));
	
	//Add Ryzen CPU Info Text ( Static )
	TxtHandle = TEXT_CreateEx( 120, 10, 110, 20, 0, WM_CF_SHOW, 0, ID_TEXT_0, "Ryzen 7 3800X");
	TEXT_SetFont(TxtHandle, GUI_FONT_8X16);	
	TEXT_SetBkColor(TxtHandle, GUI_BLACK);
	TEXT_SetTextColor( TxtHandle, GUI_RED);	
	
	//Add Ryzen Temp Text ( Dynamic )
	GUIHandle.RyzenTempTxtHandle = TEXT_CreateEx( 120, 40, 110, 20, 0, WM_CF_SHOW, 0, ID_TEXT_1, "");
	TEXT_SetFont(GUIHandle.RyzenTempTxtHandle, GUI_FONT_8X16);
	TEXT_SetBkColor(GUIHandle.RyzenTempTxtHandle, GUI_BLACK);
	TEXT_SetTextColor(GUIHandle.RyzenTempTxtHandle, GUI_RED);
	
	//Add Nvidia GPU Info Text ( Static )
	TxtHandle = TEXT_CreateEx( (LCD_SIZE_X/2)+120, 10, 110, 20, 0, WM_CF_SHOW, 0, ID_TEXT_0, "RTX 2060");
	TEXT_SetFont(TxtHandle, GUI_FONT_8X16);	
	TEXT_SetBkColor(TxtHandle, GUI_BLACK);
	TEXT_SetTextColor( TxtHandle, GUI_GREEN);		
	
	//Add Nvidia GPU Temp Text ( Dynamic )
	GUIHandle.NvidiaTempTxtHandle = TEXT_CreateEx( (LCD_SIZE_X/2)+120, 40, 110, 20, 0, WM_CF_SHOW, 0, ID_TEXT_1, "");
	TEXT_SetFont(GUIHandle.NvidiaTempTxtHandle, GUI_FONT_8X16);
	TEXT_SetBkColor(GUIHandle.NvidiaTempTxtHandle, GUI_BLACK);
	TEXT_SetTextColor(GUIHandle.NvidiaTempTxtHandle, GUI_GREEN);
	
	//Add RAM total and Usage Info Text ( Static )
	TxtHandle = TEXT_CreateEx( (LCD_SIZE_X/2), LCD_SIZE_Y - 65 , 180, 40, 0, WM_CF_SHOW, 0, ID_TEXT_0, "Total / RAM Usage");
	TEXT_SetFont(TxtHandle, GUI_FONT_8X16);	
	TEXT_SetBkColor(TxtHandle, GUI_BLACK);
	TEXT_SetTextColor( TxtHandle, GUI_CYAN);		
	
	//Add RAM total Size ( Static )
	TxtHandle = TEXT_CreateEx( (LCD_SIZE_X/2), LCD_SIZE_Y - 45 , 180, 40, 0, WM_CF_SHOW, 0, ID_TEXT_0, "16GB");
	TEXT_SetFont(TxtHandle, GUI_FONT_8X16);	
	TEXT_SetBkColor(TxtHandle, GUI_BLACK);
	TEXT_SetTextColor( TxtHandle, GUI_CYAN);

	//Add RAM Usage Text ( Dynamic )
	GUIHandle.RAMUsageTxtHandle = TEXT_CreateEx( (LCD_SIZE_X/2) + 60, LCD_SIZE_Y - 45, 110, 20, 0, WM_CF_SHOW, 0, ID_TEXT_1, "");
	TEXT_SetFont(GUIHandle.RAMUsageTxtHandle, GUI_FONT_8X16);
	TEXT_SetBkColor(GUIHandle.RAMUsageTxtHandle, GUI_BLACK);
	TEXT_SetTextColor(GUIHandle.RAMUsageTxtHandle, GUI_CYAN); 
	
	//Add Progbar for RAM Usage ( Dynamice )
	GUIHandle.RAMUsageProgHandle = PROGBAR_CreateEx((LCD_SIZE_X/2)+60 , LCD_SIZE_Y - 25, 140, 16, 0, WM_CF_SHOW, PROGBAR_CF_HORIZONTAL, ID_PROGBAR_RAM);
	PROGBAR_SetMinMax(GUIHandle.RAMUsageProgHandle, 0, 100);
	PROGBAR_GetSkinFlexProps(&RAMUsagProgBarSkinFlex, PROGBAR_SKINFLEX_L);
}
/*************************** End of file ****************************/

#include <stdlib.h>
#include <stdio.h>
// USER START (Optionally insert additional public code)
// USER END
void CPUTempUpdate(struct systemInfo_s * Info)
{
	//char sValue[32] = "";
	//sprintf(sValue,"Temp=%3.2f C",value);
	TEXT_SetText(GUIHandle.RyzenTempTxtHandle, (const char*)Info->CPUTemp);
	TEXT_SetText(GUIHandle.NvidiaTempTxtHandle, (const char*)Info->GPUTemp);
	TEXT_SetText(GUIHandle.RAMUsageTxtHandle, (const char*)Info->RAMUsage);
	
	int RAMUsage = (int)((Info->f_RAMUsed / 16.0f)*100);
	if( RAMUsage > 70 )
	{
		PROGBAR_SetBarColor(GUIHandle.RAMUsageProgHandle, 0, GUI_GREEN);
	}
	else
	{
		PROGBAR_SetBarColor(GUIHandle.RAMUsageProgHandle, 0, GUI_RED);
	}
	PROGBAR_SetValue(GUIHandle.RAMUsageProgHandle, RAMUsage);
}
/*************************** End of file ****************************/
