/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "main.h"
extern const U8 RyzenImage[26454];
extern const U8 NvidiaImage[30054];
extern struct systemInfo_s SystemInfo;
#define GUI_MAKE_COLOR(ABGR)  (((((U32)ABGR) & 0xFF000000ul) ^ 0xFF000000ul) | ((((U32)ABGR) & 0x00FF0000ul) >> 16) | (((U32)ABGR) & 0x0000FF00ul) | ((((U32)ABGR) & 0x000000FFul) << 16))
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define LCD_SIZE_X       480
#define LCD_SIZE_Y       272
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x00)
#define ID_IMAGE_0    (GUI_ID_USER + 0x04) //Ryzen Image
#define ID_IMAGE_1    (GUI_ID_USER + 0x05) //Nvidia Image
#define ID_IMAGE_2    (GUI_ID_USER + 0x07)
#define ID_TEXT_0    (GUI_ID_USER + 0x08) //RYZEN CPU Info Text
#define ID_TEXT_1    (GUI_ID_USER + 0x09) //RYZEN Temp Text
#define ID_TEXT_2    (GUI_ID_USER + 0x0A)
#define ID_TEXT_3    (GUI_ID_USER + 0x0B)

#define ID_IMAGE_0_IMAGE_0   0x00
#define ID_IMAGE_1_IMAGE_0   0x01
#define ID_IMAGE_2_IMAGE_0   0x02

// USER START (Optionally insert additional defines)
TEXT_Handle RyzenTempTxtHandle;
TEXT_Handle NvidiaTempTxtHandle;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************/

// USER START (Optionally insert additional public code)
// USER END
void CreateSystemMonitor(void)
{
	IMAGE_Handle ImgHandle;
	TEXT_Handle TxtHandle;
	//Draw two rectangles
	GUI_SetColor(GUI_RED);
	GUI_DrawRoundedRect(0,0, (LCD_SIZE_X/2)-1, LCD_SIZE_Y-2, 10);
	GUI_SetColor(GUI_GREEN);
	GUI_DrawRoundedRect((LCD_SIZE_X/2)+1, 0, LCD_SIZE_X- 2, LCD_SIZE_Y - 2, 10);
	
	//Add Ryzen BMP image
	ImgHandle = IMAGE_CreateEx(10,10, 100, 90, 0, WM_CF_SHOW, 0, ID_IMAGE_0);
	IMAGE_SetBMP(ImgHandle, RyzenImage, sizeof(RyzenImage));
	
	//Add Nvidia BMP image
	ImgHandle = IMAGE_CreateEx((LCD_SIZE_X/2)+10,10, 100, 90, 0, WM_CF_SHOW, 0, ID_IMAGE_1);
	IMAGE_SetBMP(ImgHandle, NvidiaImage, sizeof(NvidiaImage));
	
	//Add Ryzen CPU Info Text
	TxtHandle = TEXT_CreateEx( 120, 10, 110, 20, 0, WM_CF_SHOW, 0, ID_TEXT_0, "Ryzen 7 3800X");
	TEXT_SetFont(TxtHandle, GUI_FONT_8X10_ASCII);	
	TEXT_SetBkColor(TxtHandle, GUI_BLACK);
	TEXT_SetTextColor( TxtHandle, GUI_RED);	
	
	//Add Ryzen Temp Text
	RyzenTempTxtHandle = TEXT_CreateEx( 120, 40, 110, 20, 0, WM_CF_SHOW, 0, ID_TEXT_1, "");
	TEXT_SetFont(RyzenTempTxtHandle, GUI_FONT_8X16);
	TEXT_SetBkColor(RyzenTempTxtHandle, GUI_BLACK);
	TEXT_SetTextColor( RyzenTempTxtHandle, GUI_RED);
	
	//Add Nvidia GPU Info Text
	TxtHandle = TEXT_CreateEx( (LCD_SIZE_X/2)+120, 10, 110, 20, 0, WM_CF_SHOW, 0, ID_TEXT_0, "RTX 2060");
	TEXT_SetFont(TxtHandle, GUI_FONT_8X10_ASCII);	
	TEXT_SetBkColor(TxtHandle, GUI_BLACK);
	TEXT_SetTextColor( TxtHandle, GUI_GREEN);		
	
	//Add Nvidia GPU Temp Text
	NvidiaTempTxtHandle = TEXT_CreateEx( (LCD_SIZE_X/2)+120, 40, 110, 20, 0, WM_CF_SHOW, 0, ID_TEXT_1, "");
	TEXT_SetFont(NvidiaTempTxtHandle, GUI_FONT_8X16);
	TEXT_SetBkColor(NvidiaTempTxtHandle, GUI_BLACK);
	TEXT_SetTextColor( NvidiaTempTxtHandle, GUI_GREEN);
}
/*************************** End of file ****************************/

#include <stdlib.h>
#include <stdio.h>
// USER START (Optionally insert additional public code)
// USER END
void CPUTempUpdate(struct systemInfo_s * Info)
{
	//char sValue[32] = "";
	//sprintf(sValue,"Temp=%3.2f C",value);
	TEXT_SetText(RyzenTempTxtHandle, (const char*)Info->CPUTemp);
	TEXT_SetText(NvidiaTempTxtHandle, (const char*)Info->GPUTemp);
}
/*************************** End of file ****************************/
